anietchka/kids-out

- db/migrate/20210824104002_add_collumn_to_offer.rb
- db/schema.rb
- db/seeds.rb
j'ai fait 5 seed d'offers et 4 users
> seeds done

- Gemfile
- Gemfile.lock
- app/controllers/offers_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/models/offer.rb
- app/views/layouts/application.html.erb
- app/views/offers/index.html.erb
- app/views/pages/home.html.erb
- config/initializers/geocoder.rb
- config/routes.rb
- db/migrate/20210824110149_add_coordinates_to_offers.rb
- db/schema.rb
- package.json
- yarn.lock
- Création pour du dossier : views offers > index.htlm.erb
- Ajout  Gem geocoder + mapping + marker  (J'ai vérifier que le nokogiri était le même que dans  slack)
- Ajout routes :  ressources offers only index avec raccourcis dans #home pour réaliser les tests.
- Ajout méthode New/create/ index dans offers_controller
- Ajout des link pour geocoder dans <head> 
-
> Geocoding map

- app/controllers/reviews_controller.rb
- app/models/user.rb
- app/views/reviews/index.html.erb
- app/views/reviews/new.html.erb
- config/routes.rb
- db/migrate/20210824121258_add_nickname_to_user.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/reviews_controller_test.rb
j'ai créé le controlleur review ainsi que les actions index, new et create. a voir si ca fonctionne
> review controller created with all actions

- app/controllers/reviews_controller.rb
- app/policies/review_policy.rb
- config/routes.rb
j'ai rajouté les policies sur les reviews
> reviews policies done

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
- app/controllers/offers_controller.rb
- app/javascript/plugins/init_mapbox.js
- app/views/offers/_info_window.html.erb
- db/schema.rb
- Ajout Pop Up sur map avec Name/adress et link_to offer show
> Add Popup in markers and link to show offer

- app/controllers/offers_controller.rb
- app/javascript/plugins/init_autocomplete.js
- app/views/offers/index.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_searchform.html.erb
- package.json
- yarn.lock
Ajout de la barre de recherche dans l'index.
A voir demain avec TI pour adapter algolia et ajout de la recherche par age.
> Addsearchform

- app/controllers/bookmarks_controller.rb
- app/controllers/offers_controller.rb
- app/controllers/reviews_controller.rb
- app/policies/bookmark_policy.rb
- app/policies/review_policy.rb
- app/views/offers/show.html.erb
- app/views/reviews/index.html.erb
- config/routes.rb
- db/migrate/20210824145657_update_bookmark.rb
- db/schema.rb
j'ai ajouté les favoris et les commentaires a la show
> html skelett show done

- db/seeds.rb
j"ai ajouté une api mais je ne l'ai pas exploité a fond
> seeds add but not finish

- lib/tasks/maj.rb
> code pour maj

- app/models/meetup.rb
- app/views/meetups/index.html.erb
- db/schema.rb
- db/seeds.rb
j'ai changé la seed ainsi que la view des meetups
> seed changed view meetups

- app/channels/meetup_channel.rb
- app/controllers/meetups_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/participants_controller.rb
- app/javascript/channels/meetup_channel.js
- app/javascript/packs/application.js
- app/models/meetup.rb
- app/models/message.rb
- app/models/user.rb
- app/policies/meetup_policy.rb
- app/policies/message_policy.rb
- app/views/meetups/chat.html.erb
- app/views/meetups/index.html.erb
- app/views/meetups/show.html.erb
- app/views/meetups/user_meetups.html.erb
- app/views/messages/_message.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/migrate/20210830120345_create_messages.rb
- db/migrate/20210830120429_add_content_to_messages.rb
- db/schema.rb
- db/seeds.rb
- test/channels/meetup_channel_test.rb
- test/controllers/messages_controller_test.rb
- test/models/message_test.rb
- test/policies/message_policy_test.rb
ajout des messages
ajout des chatroom
ajout du js sur les chatroom
seed changée avec l'api des espaces verts
> add chat for meetups

- app/assets/stylesheets/components/_card.scss
- app/views/meetups/index.html.erb
- app/views/meetups/user_meetups.html.erb
- app/views/offers/show.html.erb
- db/migrate/20210830152444_change_date_to_date_time_in_meetups.rb
- db/migrate/20210830152830_change_text_to_string_in_messages.rb
- db/schema.rb
j'ai créé les card des meetups
> css of index user meetup done

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_flipcard.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/layouts/application.html.erb
- app/views/meetups/index.html.erb
- app/views/offers/show.html.erb
- app/views/offers/test.html.erb
**Travail sur la show de l'Offer :** 
> - refonte du front en me basant sur le figma
> - Tentative de refaire la flipcard = ECHEC à revoir avec un TA. SINON, ébauche de mise en page du INDEX MEETUP, avec lien en "commenté" sur le show de l'offer si cette solution est privilégiée.
> - Créer d'un fichier Test.html.erb pour mettre le vieux code de la show OFFER pour piochier dedans au besoin à supprimer dès qu'elle sera unutile.
> - J'ai ajouté une dimension pour les img pouvant apparaître dans les descriptifs des offers, car elles déformée la fenêtre.
**A VOIR**
> - La NavBar du bas, cache une partie du contenu (Notamment la création de nouveau commentaire à voir
> - A voir si mise en place du système de rating comme dans le figma, lien du tuto : …
> Front show offers

- app/assets/stylesheets/components/_flipcard.scss
- app/controllers/meetups_controller.rb
- app/javascript/controllers/flip_card_controller.js
- app/views/layouts/application.html.erb
- app/views/offers/show.html.erb
- db/schema.rb
- package.json
- yarn.lock
la show des offers flippe correctement
> flipp card done

- app/assets/stylesheets/components/_card.scss
- app/views/meetups/user_meetups.html.erb
- db/schema.rb
HTML + CSS pour Slide trash index meet-up réalisé. 
- En  attente de Thomas pour voir la possibilité de réaliser le slide sur l'écran.
> Slide meetup

- app/views/offers/index.html.erb
- db/schema.rb
> debug index

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/controllers/meetups_controller.rb
- app/javascript/components/toggle_trash_card.js
- app/javascript/packs/application.js
- app/views/offers/show.html.erb
- db/schema.rb
> Front form rating

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_map.scss
- app/javascript/components/toggle_favorite_card.js
- app/javascript/packs/application.js
- app/views/bookmarks/index.html.erb
- app/views/offers/_info_window.html.erb
> Réalisation de l'index Favoris avec la fonction swipe,
> Correction de la mise en page de la pop-up de la map (Décalée à cause des containers)
> Correction de conflit entre class CSS
> Front index favoris

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_flipcard.scss
- app/assets/stylesheets/components/_map.scss
- app/javascript/components/toggle_favorite_card.js
- app/javascript/packs/application.js
- app/views/bookmarks/index.html.erb
- app/views/meetups/user_meetups.html.erb
- app/views/offers/_info_window.html.erb
- app/views/offers/show.html.erb
> Mise en page de la back de la flip card
> Front back card

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/javascript/controllers/theme_selector_controller.js
- app/views/offers/index.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
agrandissement des icons sur la navbar
js de la home page fini
ajout des card des themes
> change icon navbar finish js in homepage

- app/assets/stylesheets/components/_form.scss
- app/javascript/channels/meetup_channel.js
- app/javascript/packs/application.js
- app/javascript/plugins/init_flatpickr.js
- app/views/meetups/new.html.erb
- Mise en page du formulaire New Meet up
- **Correction du JS avec Romain pour meet-up-channel**
> Front New Meetup + Correction message JS with Romain

- app/assets/stylesheets/components/_form.scss
- db/schema.rb
> Add margin top

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/pages/_home.scss
- app/javascript/plugins/init_position.js
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
home page : 
bouton et input changé de place
input changé de couleur
enlevé le scroll de la home page
fonction bouton localisé changé
> home page debug antiscrool change input

- app/assets/stylesheets/components/_map.scss
- app/views/offers/index.html.erb
- Transformed the **button** to collapse filters :
- as an icon (hamburger)
- positioned on a corner of the map
- Expanded the container of the **map** 
- now, it fills the whole screen (apart the bottom banner dedicated to the navbar)
> Filter button

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
j'ai enlevé la navbar wagon et créer une nouvelle from scrach
> new navbar kids

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_form.scss
- app/javascript/controllers/flip_card_controller.js
- app/views/meetups/show.html.erb
- app/views/offers/show.html.erb
- db/schema.rb
- Button "plus d'info"
- Front lire plus / lire moins
- Ajout d'une croix back pour le show meetup (pour retourner sur la liste des meet-up de l'offre)
- Ajout du scroll automatique à la flip card
> Correct font size

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_map.scss
- app/views/offers/index.html.erb
- app/views/offers/show.html.erb
j'ai changé la position de la card des offres sur la map car elle apparaissait mal avec la navbar sur l'iphone 8
j'ai changé la taille de certains textes depx en vw pour qu'ils apparaissent bien sur les 2 iphones
> size font change for iphone 8 and card map

- app/assets/stylesheets/components/_card.scss
- app/views/meetups/_chat.html.erb
- app/views/meetups/show.html.erb
- app/views/meetups/user_meetups.html.erb
Add participant to show meetup and correction to chatroom
> Change Chatroom + show meetup

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/javascript/controllers/theme_selector_controller.js
- app/javascript/plugins/init_mapbox.js
- app/views/pages/home.html.erb
- db/seeds.rb
lezoom de la map a été enlevé
inclusion du text des themes dans le stimulus
changement de la couleur du text inactif dans la navbar
> zoom map stimulus theme color text inactive navbar

- db/seeds.rb
j'aimis à jour les seed avec tous les parcs et les activités
> add new seeds

- app/views/shared/_navbar.html.erb
j'ai mis à jour la navbar lorsque l'on est pas connecté (identique à la connexion)
> change navbar when not  sign in

- app/assets/stylesheets/components/_form.scss
- app/controllers/profiles_controller.rb
- app/views/devise/registrations/edit.html.erb
- app/views/profiles/show.html.erb
- config/routes.rb
j'ai enlevé la couleur de fond sur la page profile et j'ai rajouté le lien pour modifier les données
j'ai mis en forme le formulaire d'edition du profile
> edit profile
